version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e GRAPHQL_ENDPOINT -e GRAPHQL_API_KEY -e GRAPHQL_TOKEN -e JWT_KEY -e JWT_API_KEY -e REDIS_ENDPOINT -e PAYMENT_PAGE_HOST >> .env.production
        - env | grep -e GRAPHQL_ENDPOINT -e GRAPHQL_API_KEY -e GRAPHQL_TOKEN -e JWT_KEY -e JWT_API_KEY -e REDIS_ENDPOINT -e PAYMENT_PAGE_HOST >> .env
        - node -v
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*